### ISSUE TITLE
script not working 

### ISSUE THREAD

**Issue by Shaunmax** [distriqt/AIR-ImageScripts#12]
I ran the following script : 

`generate.sh icon.png launch.png "#6600cc" out`

but i dont see the launch image and also the background color is still plain white.

**Comment by marchbold** [comment]
Can you elaborate some more? What output do you see in the terminal?

**Comment by Shaunmax** [comment]
> Can you elaborate some more? What output do you see in the terminal?

```
companymac@MacBook-Pro AIR-ImageScripts % sh generate.sh icon.png launch.png "#6600cc"
USING:
  icon=/Users/companymac/Projects/AIR-ImageScripts/icon.png
  launch=/Users/companymac/Projects/AIR-ImageScripts/launch.png
Generating icons
Generating Assets.car
 - Assets.car: Icons
delete /Users/companymac/Projects/AIR-ImageScripts/.air-icon-generation-tmp
delete /Users/companymac/Projects/AIR-ImageScripts/.air-icon-generation-assets/build
 - Assets.car: AppIcon created
generate_appicon: AlternateIcon.appiconset doesn't exist - creating new icon set
 - Assets.car: AlternateIcon created
 - Assets.car: launch screen
 - Assets.car: actool
 - Assets.car: actool complete
========== COMPLETE ==============
```

**Comment by marchbold** [comment]
Do you have all the dependencies installed? (xcode tools and imagemagik etc)

https://github.com/distriqt/AIR-ImageScripts#air-image-scripts

**Comment by Shaunmax** [comment]
yes

**Comment by Shaunmax** [comment]
@marchbold Also yesterday I tried to generate `Assets.car` directly using the xcode and it worked but when submitting the build for review I got the error `A 1024 x 1024 pixel app icon for your app must be added to the asset catalog`

**Comment by Shaunmax** [comment]
@marchbold when installing the build directly from app store, everything is working fine. Not sure why the same was not working with testflight builds. Closing the issue.

**Comment by marchbold** [comment]
Glad to hear,

Sometimes when testing, iOS can cache the asset catalogue even across uninstalls. Sometimes a device restart is required. Sometimes just time.
