### ISSUE TITLE
How to display the screen at the legacy resolution?

### ISSUE THREAD

**Issue by scaryama** [distriqt/AIR-ImageScripts#16]
When creating an iOS app with Adobe AIR, is there a way to display the screen at an legacy resolution?

The `requestedDisplayResolution` setting is supposed to run the app at the legacy resolution.

```
<iPhone>
    <requestedDisplayResolution>standard</requestedDisplayResolution>
</iPhone>
```

However, the app is running at the latest resolution.

My guess is that the settings in the storyboard and Assets.car file might be affecting the execution resolution, causing the app to run at the latest resolution.

Thank you.

**Comment by marchbold** [comment]
I don't believe you will pass app review attempting this, but yes I'd expect you'd need to custom create your assets catalogue to do this.

**Comment by scaryama** [comment]
That right.
If you can update to a legacy resolution, though that's the fastest way for me.
But, Following Apple's policy of emphasizing user experience, the right direction would be to work to support the latest resolution.
