### ISSUE TITLE
Deprecation of convert Command in ImageMagick - Transition to magick

### ISSUE THREAD

**Issue by gabrieloliveirabrito** [distriqt/AIR-ImageScripts#17]
We are experiencing a deprecation warning regarding the use of the `convert` command in ImageMagick version 7 (IMv7). The current implementation uses `convert` or `magick convert`, which is now deprecated.

**Warning Message:**
WARNING: The convert command is deprecated in IMv7, use "magick" instead of "convert" or "magick convert"

**Details:**

ImageMagick has updated its command-line toolset, and the `convert` command is no longer supported in IMv7. The preferred method now is to use `magick` directly for all image processing tasks.

**Impact:**

This deprecation affects our project as the current scripts and tools that utilize `convert` or `magick convert` will need to be updated to ensure compatibility with IMv7 and to avoid potential future issues.

**Proposed Solution:**

1. Update all instances of the `convert` command to use `magick`.
2. Ensure that no scripts or documentation still refer to `convert` or `magick convert`.

**Example Changes:**

- From:
```sh
convert -background none
```

- To:
 ```sh
magick -background none
```

**Action Items:**

Review the codebase for any use of convert or magick convert.
Refactor all occurrences to use magick.

Thank you!

**References:**

[ImageMagick warning message](https://github.com/ImageMagick/ImageMagick/discussions/7366)

**Comment by marchbold** [comment]
Thanks for bringing this to my attention, I'll look into it as soon as I can.

**Comment by marchbold** [comment]
This has been updated.
