### ISSUE TITLE
LaunchScreen.storyboardc

### ISSUE THREAD

**Issue by zizusoft** [distriqt/AIR-ImageScripts#2]
Is there a reason why the script outputs .storyboardc rather then .storyboard?

![image](https://user-images.githubusercontent.com/54889301/107942316-f615fd80-6f82-11eb-92e9-5508fe7204c3.png)

Or is it just a typo in the script?

Thanks

**Comment by marchbold** [comment]
storyboardc file is a compiled storyboard. That is the file you should use to package in your application.
