### ISSUE TITLE
Conflict in file name : LaunchScreen.storyboardc/Info.plist - HARMAN?

### ISSUE THREAD

**Issue by zizusoft** [distriqt/AIR-ImageScripts#3]
When i compile my IPA for release, I get this message:

![image](https://user-images.githubusercontent.com/54889301/107950859-48f5b200-6f8f-11eb-82c7-9520abc99576.png)

And the compile fails.

If I remove LaunchScreen.storyboardc from the packaging it works fine.

Is this because HARMAN is packaging their own LaunchScreen.storyboardc file (in the free version) - and you're only allowed one, therefore I am not allowed to package my own?

Thanks

**Comment by marchbold** [comment]
Yes you cannot use a custom launch screen with the free tier of the AIR SDK.
