### ISSUE TITLE
Splash screen not loaded immediately

### ISSUE THREAD

**Issue by avivmu** [distriqt/AIR-ImageScripts#4]
I've followed the tutorial for generating Assset.car and Launchscreen directory. 
I've uploaded [both files](https://gofile.io/d/EHIqov) that are packaged in my root build ios directory.

Also added

    <key>UILaunchStoryboardName</key>
    <string>LaunchScreen</string>

to `InfoAdditions`
But still I see a black screen for a moment before the splash screen. 
Any help appreciated. Note we have a license for AIR SDK

attached a video showing the problem
https://user-images.githubusercontent.com/19804341/119830628-2582c180-bf05-11eb-87da-d15da5a56fe1.mov

**Comment by marchbold** [comment]
Only just saw this question, probably best to post in the AIR discussion forum, see if anyone there has any advice. 

https://github.com/airsdk/Adobe-Runtime-Support/discussions

This could depend on the version of AIR you are using...
