### ISSUE TITLE
Assets.car file not created, but i see different sizes images

### ISSUE THREAD

**Issue by wonderdragons** [distriqt/AIR-ImageScripts#8]
Hi, 
After following steps, I see these messages in console

- Assets.car: Icons
 - Assets.car: Icons created
convert: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG `/Volumes/PWD/0. AssetCreatorForIos/AIR-ImageScripts-master/assets/Assets.xcassets/LaunchImage.imageset/LaunchImage.png' @ warning/png.c/MagickPNGWarningHandler/1748.
 - Assets.car: actool
 - Assets.car: actool complete
cp: /Volumes/PWD/0. AssetCreatorForIos/AIR-ImageScripts-master/tmp/Assets.car: No such file or directory
========== COMPLETE ==============

But I dont see any Assets.car file in folder, but i see icons of different size. Is it what it does or I am doing something wrong?

Thanks

**Comment by wonderdragons** [comment]
Ahh, fixed it :) from other issues

Going to Xcode > Preferences > Locations and selecting a default Command Line Tool location fixed this issue.

**Comment by marchbold** [comment]
Hi, yeah sometimes the location to the command line tools gets messed eg points to a beta version

You can generally correct it by running `xcode-select`:

```
sudo xcode-select -s /Applications/Xcode.app
```

More info: https://maximbilan.medium.com/switch-command-line-tools-to-xcode-beta-2e99c54cb147
